---
- name: DEPLOYMENT E CONFIGURAÇÃO SEGURA DA PILHA ELK
  hosts: localhost                        
  become: true                            
  vars:
    logstash_input_port: 5044
    compose_path: "{{ playbook_dir }}"

  vars_files:
    - secrets.yml 

  tasks:

    - name: 0.1 INSTALAR FIREWALL - Garantir que o UFW está instalado
      ansible.builtin.package:
        name: ufw
        state: present

    - name: 0.12 INSTALAR DEPENDÊNCIAS - Garantir que o Python e o pip estão instalados
      ansible.builtin.package:
        name: 
          - python3
          - python3-pip
        state: present
        update_cache: true

    - name: 0.13 INSTALAR MÓDULOS - Instalar módulos Python do requirements.txt
      ansible.builtin.pip:
        requirements: "{{ compose_path }}/requirements.txt" # O ficheiro lista as dependências
        state: present
        executable: pip3
        extra_args: "--break-system-packages"

    - name: 0.2 CONFIGURAR LOGSTASH - Copiar o logstash.conf com credenciais do Vault
      ansible.builtin.template:
        src: logstash.conf.j2
        dest: "{{ compose_path }}/logstash/pipeline/logstash.conf"
        mode: '0644'

    - name: 1.0 INSTALAR DOCKER E DEPENDENCIAS
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose
          - python3-docker
        state: present
        update_cache: true

    - name: 1.1 GARANTIR SERVIÇO - Verificar que o Docker Daemon está a correr
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: 2.2 DEPLOYMENT - Levantar o ELK Stack via Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ compose_path }}"
        state: present

    - name: 2.3 CONFIGURAR SERVIÇO SYSTEMD
      ansible.builtin.template:
        src: sensor_service.service.j2
        dest: /etc/systemd/system/sensor_service.service

    - name: 3.1 FIREWALL - Permitir tráfego TCP na porta do Logstash ({{ logstash_input_port }})
      community.general.ufw:
        rule: allow
        port: '{{ logstash_input_port }}'
        proto: tcp
        direction: in              
        state: enabled
      

    - name: 4.1 AGUARDAR CHECK - Esperar que o Elasticsearch esteja UP (API :9200) com Auth
      ansible.builtin.uri:
        url: "http://localhost:9200/_cat/health"
        method: GET
        user: "{{ elastic_user }}"          # Usa a variável desencriptada do Vault
        password: "{{ elastic_password }}"  # Usa a variável desencriptada do Vault
        status_code: 200
        validate_certs: false
      register: es_status
      until: es_status.status == 200
      retries: 30
      delay: 5
      
    - name: 4.2 CONFIGURAR KIBANA USER - Definir a password do utilizador kibana_system
      ansible.builtin.uri:
        url: "http://localhost:9200/_security/user/kibana_system/_password"
        method: POST
        user: "{{ elastic_user }}"        
        password: "{{ elastic_password }}" 
        force_basic_auth: true
        body_format: json
        body:
          password: "changeme"  # <--- A password que quer definir para o kibana_system
        status_code: 200
        validate_certs: false   
      
    - name: 5.1 ATIVAR SERVIÇO PYTHON DE LEITURA
      ansible.builtin.systemd:
        name: sensor_service
        state: started
        enabled: true
        daemon_reload: true 


    - name: 6.1 DEPENDÊNCIAS - Instalar biblioteca elasticsearch para Python
      ansible.builtin.pip:
        name: elasticsearch
        executable: pip3
        state: present
        extra_args: "--break-system-packages"

    - name: 6.2 DIRETORIA - Criar pasta para o script de monitorização
      ansible.builtin.file:
        path: /opt/monitorizacao
        state: directory
        mode: '0755'

    - name: 6.3 SCRIPT - Copiar script de alerta com credenciais seguras
      ansible.builtin.template:
        src: alert_system.py.j2
        dest: /opt/monitorizacao/alert_system.py
        mode: '0744'
      notify: Reiniciar Alerta Service

    - name: 6.4 SERVICE - Configurar serviço systemd para o alerta
      ansible.builtin.template:
        src: alert_service.service.j2
        dest: /etc/systemd/system/alert_service.service
        mode: '0644'
      notify: Reiniciar Alerta Service

    - name: 6.5 ATIVAR - Iniciar o serviço de alertas
      ansible.builtin.systemd:
        name: alert_service
        state: started
        enabled: true
        daemon_reload: true

  handlers:
   - name: Reiniciar Sensor Service
     ansible.builtin.service:
      name: sensor_service
      state: restarted
   - name: Reiniciar Alerta Service
     ansible.builtin.service:
      name: alert_service
      state: restarted
